//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcConfig {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ArcResource {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ArcResource() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcConfig.ArcResource", typeof(ArcResource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT  ad_pinfo.portnumber,ad_pinfo.id_proto,ad_sinfo.id_lsttbl,ad_list.id_type, sys_otyp.alias,ad_service.NAME,ad_service.define_alias
		/// FROM ad_dir,ad_dir dir1,ad_list,ad_pinfo,ad_ncard,ad_sinfo,sys_otyp,ad_service,ad_hosts
		/// WHERE ad_sinfo.id_server_node = ad_dir.ID
		/// AND ad_list.id_node = ad_dir.ID
		/// AND ad_pinfo.id_param = ad_list.ID
		/// AND ad_pinfo.id_intrface_node = ad_ncard.id_node
		/// AND ad_list.id_type = sys_otyp.ID
		/// AND ad_pinfo.portnumber = ad_service.ID
		/// AND ad_pinfo.id_intrface_node = dir1.ID [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string AD_SERVICE1 {
			get {
				return ResourceManager.GetString("AD_SERVICE1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT
		///    ARC_GINFO.ID as ID,
		///    sys_gtopt.NAME as VIEW_ARCHIVE,
		///    ARC_GINFO.ID_GTOPT ,
		///    sys_gtopt.DEFINE_ALIAS as DEFINE_ALIAS,
		///    ARC_TYPE.NAME as TYPE_ARCHIVE,
		///    ARC_GINFO.ID_TYPE as ID_TYPE,
		///    ARC_GINFO.DEPTH ,
		///    ARC_GINFO.DEPTH_LOCAL ,
		///    ARC_GINFO.CACHE_SIZE ,
		///    ARC_GINFO.CACHE_TIMEOUT ,
		///    ARC_GINFO.FLUSH_INTERVAL ,
		///    ARC_GINFO.RESTORE_INTERVAL ,
		///    ARC_GINFO.STACK_INTERVAL ,
		///    ARC_GINFO.WRITE_MINMAX  ,
		///    ARC_GINFO.RESTORE_TIME ,
		///    ARC_GINFO.NAME  ,
		///    ARC [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string ARC_GINFO1 {
			get {
				return ResourceManager.GetString("ARC_GINFO1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID_GTOPT  FROM ARC_GINFO WHERE ID={0}.
		/// </summary>
		internal static string ARC_GINFO2 {
			get {
				return ResourceManager.GetString("ARC_GINFO2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to    SELECT p.id_tbllst, db.NAME AS tbllst_name, t.NAME AS tbllst_tblname,
		///          ta.NAME AS arc_tblname, ag.id_gtopt, gt.NAME AS gtopt_name,
		///          gt.alias AS gtopt_alias, gt.INTERVAL AS gtopt_interval, p.id_ginfo,
		///          ag.NAME AS ginfo_name, acc.retro_depth
		///     FROM arc_subsyst_profile p,
		///          sys_db_part db,
		///          sys_tbllst t,
		///          sys_tbllst ta,
		///          sys_tbllnk tlnk,
		///          arc_ginfo ag,
		///          sys_gtopt gt,
		///          arc_services_access acc
		///    WHERE t.I [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string arc_retroviewable_v {
			get {
				return ResourceManager.GetString("arc_retroviewable_v", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to    SELECT   from_dt1970 (arc_subsyst_profile.last_update) last_update,
		///            arc_stat.avg_process, arc_stat.avg_insert, arc_stat.avg_row,
		///            arc_stat.avg_error, sys_gtopt.alias opt_alias,
		///            sys_tbllst.table_name tbl_name
		///       FROM sys_tbllst, sys_gtopt, arc_stat, arc_ginfo, arc_subsyst_profile
		///      WHERE sys_tbllst.ID = arc_stat.id_tbllst
		///        AND sys_gtopt.ID = arc_ginfo.id_gtopt
		///        AND arc_stat.id_ginfo = arc_ginfo.ID
		///        AND arc_subsyst_profile.id_tbllst =  [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string arc_stat_avg_v {
			get {
				return ResourceManager.GetString("arc_stat_avg_v", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to   SELECT   from_dt1970 (arc_subsyst_profile.last_update) last_update,
		///            arc_stat.cur_process, arc_stat.cur_insert, arc_stat.cur_row,
		///            arc_stat.cur_error, sys_gtopt.alias opt_alias,
		///            sys_tbllst.table_name tbl_name
		///       FROM sys_tbllst, sys_gtopt, arc_stat, arc_ginfo, arc_subsyst_profile
		///      WHERE sys_tbllst.ID = arc_stat.id_tbllst
		///        AND sys_gtopt.ID = arc_ginfo.id_gtopt
		///        AND arc_stat.id_ginfo = arc_ginfo.ID
		///        AND arc_subsyst_profile.id_tbllst = a [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string arc_stat_current_v {
			get {
				return ResourceManager.GetString("arc_stat_current_v", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT  asp.ID,asp.ID_TBLLST,asp.ID_GINFO
		///FROM  ARC_SUBSYST_PROFILE asp
		///.
		/// </summary>
		internal static string ARC_SUBSYST_PROFILE_ALL {
			get {
				return ResourceManager.GetString("ARC_SUBSYST_PROFILE_ALL", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID+1 FROM ARC_SUBSYST_PROFILE WHERE ID+1 NOT IN (SELECT ID FROM ARC_SUBSYST_PROFILE ).
		/// </summary>
		internal static string ARC_SUBSYST_PROFILE_ID {
			get {
				return ResourceManager.GetString("ARC_SUBSYST_PROFILE_ID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT  ARC_SUBSYST_PROFILE.ID,ARC_SUBSYST_PROFILE.ID_TBLLST,ARC_SUBSYST_PROFILE.ID_GINFO,
		///  ARC_SUBSYST_PROFILE.IS_WRITEON, ARC_SUBSYST_PROFILE.STACK_NAME,ARC_SUBSYST_PROFILE.LAST_UPDATE,ARC_SUBSYST_PROFILE.IS_VIEWABLE
		///FROM  ARC_SUBSYST_PROFILE
		///WHERE  {0}=ARC_SUBSYST_PROFILE.ID_TBLLST.
		/// </summary>
		internal static string ARC_SUBSYST_PROFILE1 {
			get {
				return ResourceManager.GetString("ARC_SUBSYST_PROFILE1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT  a.ID, a.ID_GINFO,a.IS_WRITEON, ARC_GINFO.NAME, SYS_GTOPT.NAME
		///FROM  ARC_SUBSYST_PROFILE a, ARC_GINFO, SYS_GTOPT
		///WHERE a.ID_GINFO=ARC_GINFO.ID
		///AND SYS_GTOPT.ID=ARC_GINFO.ID_GTOPT 
		///AND a.ID_TBLLST={0}.
		/// </summary>
		internal static string ARC_SUBSYST_PROFILE2 {
			get {
				return ResourceManager.GetString("ARC_SUBSYST_PROFILE2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT  a.ID, a.ID_GINFO, a.IS_WRITEON 
		///FROM  ARC_SUBSYST_PROFILE a
		///WHERE {0}=a.ID_TBLLST AND a.ID_GINFO={1}.
		/// </summary>
		internal static string ARC_SUBSYST_PROFILE3 {
			get {
				return ResourceManager.GetString("ARC_SUBSYST_PROFILE3", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT  a.ID, a.ID_GINFO, ARC_GINFO.NAME, ARC_GINFO.ID_GTOPT, SYS_GTOPT.NAME
		///FROM  ARC_SUBSYST_PROFILE a, ARC_GINFO, SYS_GTOPT
		///WHERE a.ID_GINFO=ARC_GINFO.ID
		///AND SYS_GTOPT.ID=ARC_GINFO.ID_GTOPT 
		///AND SYS_GTOPT.DEFINE_ALIAS NOT LIKE &apos;GLT_ANALOG_OPT_INSTANT%&apos; 
		///AND SYS_GTOPT.DEFINE_ALIAS NOT LIKE &apos;GLT_ANALOG_OPT_CUR%&apos; 
		///AND SYS_GTOPT.DEFINE_ALIAS NOT LIKE &apos;GLT_DANALOG_OPT_INSTANT%&apos; 
		///AND a.ID_TBLLST={0}.
		/// </summary>
		internal static string ARC_SUBSYST_PROFILE5 {
			get {
				return ResourceManager.GetString("ARC_SUBSYST_PROFILE5", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID,ID_GINFO,ID_TBLLST,DEPTH,IS_ACTIVE,TABLE_NAME,DT_START,DT_END
		///   , &apos;0&apos; AS CNT, FROM_DT1970(DT_START) AS DATESTART,  FROM_DT1970(DT_END) AS DATEEND 
		///FROM  {0}
		///WHERE ID_GINFO= {1} AND ID_TBLLST= {2}
		///ORDER BY ID.
		/// </summary>
		internal static string ARC_VIEW_PARTITIONS1 {
			get {
				return ResourceManager.GetString("ARC_VIEW_PARTITIONS1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID,ID_GINFO,ID_TBLLST,DEPTH,IS_ACTIVE,TABLE_NAME,DT_START,DT_END
		///   , &apos;0&apos; AS CNT, &apos;0&apos; AS DATESTART,  &apos;0&apos; AS DATEEND
		///FROM  {0}
		///WHERE ID_GINFO= {1} AND ID_TBLLST= {2}
		///ORDER BY ID.
		/// </summary>
		internal static string ARC_VIEW_PARTITIONS2 {
			get {
				return ResourceManager.GetString("ARC_VIEW_PARTITIONS2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT upper(lst.table_name) , lnk.ID_LSTTBL
		///FROM sys_tbllst lst, sys_tbllnk lnk, sys_otyp t
		///WHERE lnk.id_dsttbl = lst.ID  AND lst.id_type = t.ID AND t.define_alias LIKE &apos;ARH&apos;
		/// AND  lnk.id_lsttbl = {0}.
		/// </summary>
		internal static string ARH_SYSTBLLST1 {
			get {
				return ResourceManager.GetString("ARH_SYSTBLLST1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to select DISTINCT y.ID id_tbllst, y.table_name lst_tblname, x.table_name arc_tblname, sch.SCHEMA_NAME
		///               from sys_tbllst x, sys_tbllst y, sys_tbllnk st, sys_otyp ot, arc_db_schema sch, arc_services_info si
		///              where y.ID = st.id_lsttbl
		///                and x.ID = st.id_dsttbl
		///                and x.id_type = ot.id
		///                and ot.define_alias = &apos;ARH&apos;
		///                and si.ID_DB_SCHEMA = sch.ID
		///                and si.ID_LSTTBL = y.ID
		///                and y.ID = {0}
		///          [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string ARH_SYSTBLLST2 {
			get {
				return ResourceManager.GetString("ARH_SYSTBLLST2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to select DISTINCT y.ID id_tbllst, sch.SCHEMA_NAME, ast.DEFINE_ALIAS
		///from sys_tbllst x, sys_tbllst y, sys_tbllnk st, sys_otyp ot, arc_db_schema sch, arc_services_info si, ARC_STORAGE_TYPE ast
		///where y.ID = st.id_lsttbl
		///                and x.ID = st.id_dsttbl
		///                and x.id_type = ot.id
		///                and ot.define_alias = &apos;ARH&apos;
		///                and si.ID_DB_SCHEMA = sch.ID
		///                and si.ID_LSTTBL = y.ID
		///                and ast.ID = sch.ID_STORAGE_TYPE
		///                and y.ID = {0}
		/// [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string ARH_SYSTBLLST3 {
			get {
				return ResourceManager.GetString("ARH_SYSTBLLST3", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to   SELECT ID, id_obj, id_meas_type, NAME, alias, 0 as ID_GINFO
		///     FROM meas_list
		///    WHERE id_meas_type IN (SELECT ID
		///                             FROM sys_meas_types
		///                            WHERE define_alias LIKE &apos;MEAS_SIGNAL_STATE%&apos;)
		///      AND is_exdata = 0
		///  UNION
		///    SELECT ID, id_obj, id_meas_type, NAME, alias, MEAS_ARC.ID_GINFO as ID_GINFO
		///     FROM meas_list , MEAS_ARC
		///    WHERE id_meas_type IN (SELECT ID
		///                             FROM sys_meas_types
		///                            WH [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string AUTO_LIST_V {
			get {
				return ResourceManager.GetString("AUTO_LIST_V", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AUTO_LIST_V.
		/// </summary>
		internal static string AUTO_LIST_V0 {
			get {
				return ResourceManager.GetString("AUTO_LIST_V0", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to   SELECT ID, id_obj, id_meas_type, NAME, alias, 0 as ID_GINFO
		///     FROM meas_list
		///    WHERE id_meas_type IN (SELECT ID
		///                             FROM sys_meas_types
		///                            WHERE define_alias LIKE &apos;MEAS_SIGNAL_STATE%&apos;)
		///  UNION
		///    SELECT ID, id_obj, id_meas_type, NAME, alias, MEAS_ARC.ID_GINFO as ID_GINFO
		///     FROM meas_list , MEAS_ARC
		///    WHERE id_meas_type IN (SELECT ID
		///                             FROM sys_meas_types
		///                            WHERE define_alias LIKE &apos;ME [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string AUTO_LIST_V1 {
			get {
				return ResourceManager.GetString("AUTO_LIST_V1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to    SELECT ID, id_node,  0 as ID_TYPE, NAME, alias , 0 as ID_GINFO
		///     FROM CALC_LIST
		///   UNION
		///   SELECT ID, id_node,  0 as ID_TYPE, NAME, alias , CALC_ARC.ID_GINFO as ID_GINFO
		///     FROM CALC_LIST , CALC_ARC
		///   WHERE
		///   CALC_LIST.ID=CALC_ARC.ID_PARAM
		///  ORDER BY ID ASC.
		/// </summary>
		internal static string CALC_LIST {
			get {
				return ResourceManager.GetString("CALC_LIST", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to    SELECT {0}.ID_NODE, DA_CAT.NAME, {0}.ID,
		///          (CASE
		///              WHEN REGEXP_LIKE (gt.define_alias, &apos;ANALOG&apos;)
		///                 THEN &apos;ТИ&apos;
		///              WHEN REGEXP_LIKE (gt.define_alias, &apos;TELECONTROL&apos;)
		///                 THEN &apos;ТУ&apos;
		///              WHEN REGEXP_LIKE (gt.define_alias, &apos;BOOL&apos;)
		///                 THEN &apos;ТС&apos;
		///              ELSE &apos;??&apos;
		///           END
		///          ) AS ID_TYPE,
		///          {0}.NAME,
		///          0 as ID_GINFO
		///     FROM DA_CAT 
		///     JOIN {0} ON DA_CAT.ID = {0}.ID_NODE
		///     JOIN  [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string DA_V_LST {
			get {
				return ResourceManager.GetString("DA_V_LST", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT {0}.ID_NODE, DA_CAT.NAME, {0}.ID, {0}.ID_TYPE, {0}.NAME, 0 as ID_GINFO
		///FROM {0}, DA_CAT
		///WHERE
		/// DA_CAT.ID={0}.ID_NODE
		///UNION
		///SELECT {0}.ID_NODE, DA_CAT.NAME, {0}.ID, {0}.ID_TYPE, {0}.NAME, DA_ARC.ID_GINFO as ID_GINFO
		///FROM {0}, DA_CAT, DA_ARC
		///WHERE {0}.ID=DA_ARC.ID_PARAM
		///and DA_CAT.ID={0}.ID_NODE
		///ORDER BY ID_NODE, ID .
		/// </summary>
		internal static string DA_V_LST_TMP {
			get {
				return ResourceManager.GetString("DA_V_LST_TMP", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to    SELECT ID, id_node, 0 as ID_TYPE, NAME, alias , 0 as ID_GINFO
		///     FROM DG_LIST
		///   UNION
		///   SELECT ID, id_node,  0 as ID_TYPE, NAME, alias , DG_ARC.ID_GINFO as ID_GINFO
		///     FROM DG_LIST , DG_ARC
		///   WHERE
		///   DG_LIST.ID=DG_ARC.ID_PARAM
		///  ORDER BY ID ASC.
		/// </summary>
		internal static string DG_LIST {
			get {
				return ResourceManager.GetString("DG_LIST", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to    SELECT ID, id_node,  0 as ID_TYPE, NAME, alias , 0 as ID_GINFO
		///     FROM EA_CHANNELS
		///   UNION
		///   SELECT ID, id_node,  0 as ID_TYPE, NAME, alias , EA_ARC.ID_GINFO as ID_GINFO
		///     FROM EA_CHANNELS, EA_ARC
		///   WHERE
		///   EA_CHANNELS.ID=EA_ARC.ID_PARAM
		///  ORDER BY ID ASC.
		/// </summary>
		internal static string EA_CHANNELS {
			get {
				return ResourceManager.GetString("EA_CHANNELS", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to    SELECT ea_points.ID, ea_points.id_node,
		///          ea_points.id_type, ea_points.NAME,
		///          ea_points.alias, 0 as ID_GINFO
		///     FROM ea_channels ea_points, ea_consumer_link
		///    WHERE ea_points.ID = ea_consumer_link.id_point(+)
		///    UNION
		///   SELECT ea_points.ID, ea_points.id_node,
		///          ea_points.id_type, ea_points.NAME,
		///          ea_points.alias, EA_ARC.ID_GINFO as ID_GINFO
		///     FROM ea_channels ea_points, ea_consumer_link, EA_ARC
		///    WHERE ea_points.ID = ea_consumer_link.id_point(+)
		/// AN [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string EA_V_CONSUMER_POINTS {
			get {
				return ResourceManager.GetString("EA_V_CONSUMER_POINTS", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID, id_obj, id_meas_type, NAME, alias , 0 as  ID_GINFO
		///FROM meas_list
		///WHERE id_meas_type IN (
		/// SELECT m.ID FROM sys_meas_types m, sys_ptyp t WHERE m.id_type = t.ID AND t.id_node = 1
		///) AND is_exdata = 0
		///UNION
		///SELECT ID, id_obj, id_meas_type, NAME, alias , MEAS_ARC.ID_GINFO  as  ID_GINFO
		///FROM meas_list , MEAS_ARC
		///WHERE id_meas_type IN (
		///  SELECT m.ID FROM sys_meas_types m, sys_ptyp t WHERE m.id_type = t.ID AND t.id_node = 1
		///) AND is_exdata = 0
		/// AND MEAS_LIST.ID=MEAS_ARC.ID_PARAM
		/// ORDER BY I [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string ELREG_LIST_V {
			get {
				return ResourceManager.GetString("ELREG_LIST_V", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ELREG_LIST_V.
		/// </summary>
		internal static string ELREG_LIST_V0 {
			get {
				return ResourceManager.GetString("ELREG_LIST_V0", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID, id_obj, id_meas_type, NAME, alias
		///FROM meas_list
		///WHERE id_meas_type IN (
		/// SELECT m.ID FROM sys_meas_types m, sys_ptyp t WHERE m.id_type = t.ID AND t.id_node = 1
		///).
		/// </summary>
		internal static string ELREG_LIST_V00 {
			get {
				return ResourceManager.GetString("ELREG_LIST_V00", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID, id_obj, id_meas_type, NAME, alias , 0 as  ID_GINFO
		///FROM meas_list
		///WHERE id_meas_type IN (
		/// SELECT m.ID FROM sys_meas_types m, sys_ptyp t WHERE m.id_type = t.ID AND t.id_node = 1
		///) 
		///UNION
		///SELECT ID, id_obj, id_meas_type, NAME, alias , MEAS_ARC.ID_GINFO  as  ID_GINFO
		///FROM meas_list , MEAS_ARC
		///WHERE id_meas_type IN (
		///  SELECT m.ID FROM sys_meas_types m, sys_ptyp t WHERE m.id_type = t.ID AND t.id_node = 1
		///) 
		/// AND MEAS_LIST.ID=MEAS_ARC.ID_PARAM
		/// ORDER BY ID ASC  .
		/// </summary>
		internal static string ELREG_LIST_V1 {
			get {
				return ResourceManager.GetString("ELREG_LIST_V1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID, id_obj AS id_node, id_meas_type, NAME, alias, 0 as ID_GINFO
		///FROM meas_list
		///WHERE  is_exdata = 1
		/// UNION
		///SELECT ID, id_obj AS id_node, id_meas_type, NAME, alias, MEAS_ARC.ID_GINFO as ID_GINFO
		///FROM meas_list , MEAS_ARC
		///WHERE  is_exdata = 1
		///  AND MEAS_LIST.ID=MEAS_ARC.ID_PARAM
		/// ORDER BY ID ASC   .
		/// </summary>
		internal static string EXDATA_LIST_V {
			get {
				return ResourceManager.GetString("EXDATA_LIST_V", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT arcs.ID_SERVICE, ads.NAME , arcs.PRIORITY
		///FROM ARC_SERVICES_TUNE arcs, AD_SERVICE ads 
		///WHERE ads.ID=arcs.ID_SERVICE and arcs.ID_SPROFILE={0}
		///union
		///SELECT arcs.ID_SERVICE, &apos;?????????????????&apos; as NAME , 0 as PRIORITY
		///FROM ARC_SERVICES_TUNE arcs, AD_SERVICE ads 
		///WHERE arcs.ID_SERVICE not in (SELECT id FROM AD_SERVICE)
		///and arcs.ID_SPROFILE={0}.
		/// </summary>
		internal static string FormSERVICE1 {
			get {
				return ResourceManager.GetString("FormSERVICE1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT arcs.ID_SERVICE, ads.NAME , arcs.RETRO_DEPTH
		///FROM ARC_SERVICES_ACCESS arcs, AD_SERVICE ads 
		///WHERE ads.ID=arcs.ID_SERVICE and arcs.ID_SPROFILE={0}
		///union
		///SELECT arcs.ID_SERVICE, &apos;?????????????????&apos; as NAME , 0 as RETRO_DEPTH
		///FROM ARC_SERVICES_ACCESS arcs, AD_SERVICE ads 
		///WHERE arcs.ID_SERVICE not in (SELECT id FROM AD_SERVICE)
		///and arcs.ID_SPROFILE={0}.
		/// </summary>
		internal static string FormSERVICE2 {
			get {
				return ResourceManager.GetString("FormSERVICE2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT 
		///  SYS_GTOPT.ID
		///  ,SYS_GTOPT.NAME
		///  ,SYS_GTYP.DEFINE_ALIAS as \&quot;DataType\&quot; 
		///  ,SYS_GTOPT.INTERVAL as \&quot;Interval (sec)\&quot;
		///  ,&apos;0&apos; as \&quot;Archive Type\&quot; 
		///FROM SYS_GTOPT, SYS_GTYP 
		///WHERE SYS_GTOPT.ID_ATYPE is null and SYS_GTYP.id=SYS_GTOPT.ID_GTYPE 
		/// union 
		///SELECT 
		///  SYS_GTOPT.ID
		///  ,SYS_GTOPT.NAME
		///  ,SYS_GTYP.DEFINE_ALIAS as \&quot;DataType\&quot; 
		///  ,SYS_GTOPT.INTERVAL as \&quot;Interval (sec)\&quot; 
		///  ,SYS_ATYP.NAME as \&quot;Archive Type\&quot; 
		///FROM SYS_GTOPT , SYS_ATYP, SYS_GTYP 
		///WHERE SYS_GTOPT.ID_ATYPE=SYS_ATYP.I [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string GTOPT1 {
			get {
				return ResourceManager.GetString("GTOPT1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT sgt.ID, sgt.NAME, sgt.ALIAS, sgt.DEFINE_ALIAS, sgt.INTERVAL, 
		///sgtp.NAME as GTYP, sgtp.DEFINE_ALIAS as GTYPD, 
		///sat.NAME AS ATYP , sat.DEFINE_ALIAS AS ADEF 
		///FROM SYS_GTOPT sgt, SYS_GTYP sgtp, SYS_ATYP sat 
		///WHERE sgt.ID_GTYPE = sgtp.ID and sgt.ID_ATYPE = sat.ID 
		///UNION 
		///SELECT sgt.ID, sgt.NAME, sgt.ALIAS, sgt.DEFINE_ALIAS, sgt.INTERVAL, 
		///sgtp.NAME as GTYP, sgtp.DEFINE_ALIAS as GTYPD, 
		///&apos;&apos; AS ATYP , &apos;&apos; AS ADEF
		///FROM SYS_GTOPT sgt, SYS_GTYP sgtp  
		///WHERE sgt.ID_GTYPE = sgtp.ID and ( sgt.ID_ATYPE=&apos;&apos;  [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string GTOPT2 {
			get {
				return ResourceManager.GetString("GTOPT2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT mst.ID, ot.NAME as Object, mst.PARAM_TYPE, mst.NAME, mst.STATUS, mst.DT1970
		///-- FROM MEAS_SNAPSHOT30_TUNE mst, OBJ_TREE ot
		///FROM {0} mst, {1} ot
		///WHERE mst.ID_OBJ=ot.ID.
		/// </summary>
		internal static string MEAS_SNAPSHOT30_TUNE_t {
			get {
				return ResourceManager.GetString("MEAS_SNAPSHOT30_TUNE_t", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to   SELECT ID, id_obj, id_meas_type, NAME, alias, 0 as ID_GINFO
		///     FROM meas_list
		///    WHERE id_meas_type IN (
		///   SELECT m.ID FROM sys_meas_types m, sys_ptyp t
		///    WHERE m.id_type = t.ID
		///      AND t.id_node &lt;&gt; 1
		///      AND m.define_alias NOT LIKE (&apos;MEAS_SWITCH_STATE%&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_SIGNAL_STATE%&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_STATE_EQUIP&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_START_STOP&apos;)
		///   ) AND is_exdata = 0
		///  UNION
		///  SELECT ID, id_obj, id_meas_type,  [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string PHREG_LIST_V {
			get {
				return ResourceManager.GetString("PHREG_LIST_V", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PHREG_LIST_V
		/// .
		/// </summary>
		internal static string PHREG_LIST_V0 {
			get {
				return ResourceManager.GetString("PHREG_LIST_V0", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID, id_obj, id_meas_type, NAME, alias
		///     FROM meas_list
		///    WHERE id_meas_type IN (
		///   SELECT m.ID FROM sys_meas_types m, sys_ptyp t
		///    WHERE m.id_type = t.ID
		///      AND t.id_node &lt;&gt; 1
		///      AND m.define_alias NOT LIKE (&apos;MEAS_SWITCH_STATE%&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_SIGNAL_STATE%&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_STATE_EQUIP&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_START_STOP&apos;)
		///   ) .
		/// </summary>
		internal static string PHREG_LIST_V00 {
			get {
				return ResourceManager.GetString("PHREG_LIST_V00", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to   SELECT ID, id_obj, id_meas_type, NAME, alias, 0 as ID_GINFO
		///     FROM meas_list
		///    WHERE id_meas_type IN (
		///   SELECT m.ID FROM sys_meas_types m, sys_ptyp t
		///    WHERE m.id_type = t.ID
		///      AND t.id_node &lt;&gt; 1
		///      AND m.define_alias NOT LIKE (&apos;MEAS_SWITCH_STATE%&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_SIGNAL_STATE%&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_STATE_EQUIP&apos;)
		///      AND m.define_alias NOT LIKE (&apos;MEAS_START_STOP&apos;)
		///   ) 
		///  UNION
		///  SELECT ID, id_obj, id_meas_type, NAME, alias, MEAS [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string PHREG_LIST_V1 {
			get {
				return ResourceManager.GetString("PHREG_LIST_V1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID, id_obj, id_meas_type, NAME, alias, 0 as ID_GINFO
		///FROM meas_list
		///WHERE id_meas_type IN (SELECT ID FROM sys_meas_types WHERE define_alias LIKE &apos;MEAS_SWITCH_STATE%&apos;)
		///AND is_exdata = 0
		///UNION
		///SELECT ID, id_obj, id_meas_type, NAME, alias, MEAS_ARC.ID_GINFO as ID_GINFO
		///FROM meas_list, MEAS_ARC
		///WHERE id_meas_type IN (SELECT ID FROM sys_meas_types WHERE define_alias LIKE &apos;MEAS_SWITCH_STATE%&apos;)
		/// AND is_exdata = 0
		/// AND MEAS_LIST.ID=MEAS_ARC.ID_PARAM
		///ORDER BY ID ASC .
		/// </summary>
		internal static string PSWT_LIST_V {
			get {
				return ResourceManager.GetString("PSWT_LIST_V", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PSWT_LIST_V.
		/// </summary>
		internal static string PSWT_LIST_V0 {
			get {
				return ResourceManager.GetString("PSWT_LIST_V0", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT ID, id_obj, id_meas_type, NAME, alias, 0 as ID_GINFO
		///FROM meas_list
		///WHERE id_meas_type IN (SELECT ID FROM sys_meas_types WHERE define_alias LIKE &apos;MEAS_SWITCH_STATE%&apos;)
		///UNION
		///SELECT ID, id_obj, id_meas_type, NAME, alias, MEAS_ARC.ID_GINFO as ID_GINFO
		///FROM meas_list, MEAS_ARC
		///WHERE id_meas_type IN (SELECT ID FROM sys_meas_types WHERE define_alias LIKE &apos;MEAS_SWITCH_STATE%&apos;)
		/// AND MEAS_LIST.ID=MEAS_ARC.ID_PARAM
		///ORDER BY ID ASC .
		/// </summary>
		internal static string PSWT_LIST_V1 {
			get {
				return ResourceManager.GetString("PSWT_LIST_V1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT DISTINCT a.id ,  sch.schema_name
		///FROM  arc_db_schema sch, arc_services_info si,  sys_tbllst a
		///WHERE a.ID = si.id_lsttbl AND si.id_db_schema = sch.ID and a.ID ={0}.
		/// </summary>
		internal static string SCHEMA_NAME {
			get {
				return ResourceManager.GetString("SCHEMA_NAME", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT 
		///  sg1.ID,sg1.NAME
		///  ,sg1.DEFINE_ALIAS
		///  ,sg1.INTERVAL as &quot;Interval (sec)&quot; 
		///  ,&apos;0&apos; as &quot;Archive Type&quot;
		///  ,sg2.DEFINE_ALIAS as &quot;DataType&quot; 
		/// FROM SYS_GTOPT sg1, SYS_GTYP sg2
		/// WHERE sg1.ID_ATYPE is null and sg2.id=sg1.ID_GTYPE
		/// union 
		///SELECT 
		///  sg1.ID,sg1.NAME
		///  ,sg1.DEFINE_ALIAS
		///  ,sg1.INTERVAL as &quot;Interval (sec)&quot; 
		///  ,sa.NAME as &quot;Archive Type&quot; 
		///  ,sg2.DEFINE_ALIAS as &quot;DataType&quot; 
		///FROM SYS_GTOPT sg1, SYS_ATYP sa, SYS_GTYP sg2
		/// WHERE sg1.ID_ATYPE=sa.ID and sg2.id=sg1.ID_GTYPE.
		/// </summary>
		internal static string SYS_GTOPT_LIST_V {
			get {
				return ResourceManager.GetString("SYS_GTOPT_LIST_V", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT  a.table_name
		///FROM   sys_tbllst a, SYS_TBLLNK b
		///WHERE  b.ID_DSTTBL=a.id and a.DEFINE_ALIAS like &apos;%ARH%&apos; and b.ID_LSTTBL={0}.
		/// </summary>
		internal static string TABLE_ARC {
			get {
				return ResourceManager.GetString("TABLE_ARC", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT upper(lst.TABLE_NAME) FROM sys_tbllst lst WHERE lst.ID={0}.
		/// </summary>
		internal static string TABLE_ARC1 {
			get {
				return ResourceManager.GetString("TABLE_ARC1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT &apos;min&apos; as num, TIME1970 as T FROM {0} WHERE TIME1970 = (SELECT MIN(TIME1970) FROM {0} )
		///union
		///SELECT &apos;max&apos; as num, TIME1970 as T FROM {0}  WHERE TIME1970 = (SELECT MAX(TIME1970) FROM {0} )
		///union
		///SELECT &apos;cnt&apos; as num, count(*) as T FROM {0}.
		/// </summary>
		internal static string TABLEOPTION {
			get {
				return ResourceManager.GetString("TABLEOPTION", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap v1 {
			get {
				object obj = ResourceManager.GetObject("v1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap v2 {
			get {
				object obj = ResourceManager.GetObject("v2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap v3 {
			get {
				object obj = ResourceManager.GetObject("v3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap v4 {
			get {
				object obj = ResourceManager.GetObject("v4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
