//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSDU.Components.FormulEdit.Analizer {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSDU.Components.FormulEdit.Analizer.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствуют аргументы функции.
        /// </summary>
        internal static string ArgumentsNeed {
            get {
                return ResourceManager.GetString("ArgumentsNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определен аргумент функции.
        /// </summary>
        internal static string ArgXMustBeChanged {
            get {
                return ResourceManager.GetString("ArgXMustBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует выражение.
        /// </summary>
        internal static string ExpressionMissing {
            get {
                return ResourceManager.GetString("ExpressionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на После оператора отстутствует выражение.
        /// </summary>
        internal static string ExpressionNeedAfter {
            get {
                return ResourceManager.GetString("ExpressionNeedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед оператором отстутствует выражение.
        /// </summary>
        internal static string ExpressionNeedBefore {
            get {
                return ResourceManager.GetString("ExpressionNeedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный тип аргумента.
        /// </summary>
        internal static string FuncArgErrorType {
            get {
                return ResourceManager.GetString("FuncArgErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное количество аргументов функции.
        /// </summary>
        internal static string FungErrorArgsCount {
            get {
                return ResourceManager.GetString("FungErrorArgsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует закрывающая скобка.
        /// </summary>
        internal static string NoFindBrecketCloseForThis {
            get {
                return ResourceManager.GetString("NoFindBrecketCloseForThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лишняя закрывающая скобка.
        /// </summary>
        internal static string NoFindBrecketOpenForThis {
            get {
                return ResourceManager.GetString("NoFindBrecketOpenForThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдена функция: {0}.
        /// </summary>
        internal static string NoFindFunction {
            get {
                return ResourceManager.GetString("NoFindFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден параметр с идентификатором: {0}.
        /// </summary>
        internal static string NoFindParameter {
            get {
                return ResourceManager.GetString("NoFindParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деление на ноль.
        /// </summary>
        internal static string NullDivider {
            get {
                return ResourceManager.GetString("NullDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное число.
        /// </summary>
        internal static string NumberFailed {
            get {
                return ResourceManager.GetString("NumberFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует оператор.
        /// </summary>
        internal static string OperatorNeed {
            get {
                return ResourceManager.GetString("OperatorNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верный формат параметра.
        /// </summary>
        internal static string ParamFailed {
            get {
                return ResourceManager.GetString("ParamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестное выражение.
        /// </summary>
        internal static string UnknownExpression {
            get {
                return ResourceManager.GetString("UnknownExpression", resourceCulture);
            }
        }
    }
}
