SET DEFINE OFF;
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (220, 127, 'p1', 'v1', 1, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (221, 127, 'p2', 'v2', 2, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (222, 127, 'p3', 'v3', 3, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (223, 127, 'p4', 'v4', 4, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (224, 127, 'p5', 'v5', 5, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (225, 127, 'p6', 'v6', 6, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (226, 127, 'p7', 'v7', 7, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (227, 127, 'p8', 'v8', 8, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (228, 127, 'p9', 'v9', 9, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (229, 127, 'p10', 'v10', 10, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (230, 128, 'p1', 'v1', 1, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (231, 128, 'p2', 'v2', 2, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (232, 128, 'p3', 'v3', 3, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (233, 128, 'p4', 'v4', 4, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (234, 128, 'p5', 'v5', 5, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (235, 128, 'p6', 'v6', 6, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (236, 128, 'p7', 'v7', 7, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (237, 128, 'p8', 'v8', 8, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (238, 128, 'p9', 'v9', 9, 1);
Insert into RSDUADMIN.MEAS_FUNCTION_ARGUMENT
   (ID, ID_TEMPLATE, NAME, ALIAS, ARG_POSITION, IS_STATIC)
 Values
   (239, 128, 'p10', 'v10', 10, 1);
COMMIT;
